---
  - hosts: all
    become: true
    tasks:
    -
      apt: "name=nginx state=latest"
      name: "ensure nginx is at the latest version"
    -
      name: "start nginx"
      service:
      name: nginx
      state: started